// Map icon_key (defined in the backend) -> Fluent UI React v9 icon component.
// We import a curated list of icons used across the system. If a key has no
// mapping we fall back to DocumentBulletList24Regular.

import {
  VehicleCar24Regular,
  Home24Regular,
  Building24Regular,
  Warning24Regular,
  Money24Regular,
  Person24Regular,
  DocumentBulletList24Regular,
  CalendarMonth24Regular,
  Clock24Regular,
  CheckmarkCircle24Regular,
  Search24Regular,
  Add24Regular,
  Edit24Regular,
  Delete24Regular,
  Dismiss24Regular,
  Print24Regular,
  ArrowRight24Regular,
  WeatherSunny24Regular,
  DarkTheme24Regular,
  LockClosed24Regular,
  Mail24Regular,
  Phone24Regular,
  Location24Regular,
  Tag24Regular,
  Info24Regular,
  ArrowLeft24Regular,
  ArrowExport24Regular,
  Filter24Regular,
  Save24Regular,
  ChevronRight24Regular,
  ChevronLeft24Regular,
  MoreHorizontal24Regular,
  Eye24Regular,
  EyeOff24Regular,
  Checkmark24Regular,
  Briefcase24Regular,
  Receipt24Regular,
  Shield24Regular,
  Megaphone24Regular,
  Globe24Regular,
  Headset24Regular,
  Question24Regular,
  type FluentIcon,
} from '@fluentui/react-icons';

const MAP: Record<string, FluentIcon> = {
  vehicle: VehicleCar24Regular,
  car: VehicleCar24Regular,
  home: Home24Regular,
  building: Building24Regular,
  warning: Warning24Regular,
  money: Money24Regular,
  person: Person24Regular,
  document: DocumentBulletList24Regular,
  calendar: CalendarMonth24Regular,
  clock: Clock24Regular,
  checkmark: CheckmarkCircle24Regular,
  search: Search24Regular,
  add: Add24Regular,
  edit: Edit24Regular,
  delete: Delete24Regular,
  dismiss: Dismiss24Regular,
  print: Print24Regular,
  arrow: ArrowRight24Regular,
  sun: WeatherSunny24Regular,
  moon: DarkTheme24Regular,
  lock: LockClosed24Regular,
  mail: Mail24Regular,
  phone: Phone24Regular,
  location: Location24Regular,
  tag: Tag24Regular,
  info: Info24Regular,
  back: ArrowLeft24Regular,
  export: ArrowExport24Regular,
  filter: Filter24Regular,
  save: Save24Regular,
  next: ChevronRight24Regular,
  prev: ChevronLeft24Regular,
  more: MoreHorizontal24Regular,
  show: Eye24Regular,
  hide: EyeOff24Regular,
  check: Checkmark24Regular,
  briefcase: Briefcase24Regular,
  receipt: Receipt24Regular,
  shield: Shield24Regular,
  megaphone: Megaphone24Regular,
  globe: Globe24Regular,
  headset: Headset24Regular,
  help: Question24Regular,
};

export function getIcon(key: string | null | undefined): FluentIcon {
  if (!key) return DocumentBulletList24Regular;
  return MAP[key] ?? DocumentBulletList24Regular;
}
